name: tofu-fmt-check
description: Check that OpenTofu configuration files are in canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the OpenTofu configuration
    required: false
    default: .
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:31f49b44966fdd5a6595ba90b8ca2d0226199f82c8bc1826654b00b5d8e04fc3
  entrypoint: /entrypoints/fmt-check.sh

branding:
  icon: globe
  color: purple
